name: active-exploration
dependencies:
  - python >= 3.8
  - pip
  - pip:
      - numpy
      - opencv-python
      - configargparse
      - imgui
      - glfw
      - pyopengl
      - tensorboard
      - matplotlib
      - lpips
      - mitsuba
